version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbVolume:/var/lib/postgresql/data
  todoapp:
    build: .
    container_name: todoApp
    ports:
      - "8080:8080"

volumes:
    dbVolume: