version: "3.8"
services:
  bd:
    image: postgres:latest
    container_name: bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbVolume:/var/lib/postgresql/data

volumes:
    dbVolume: