### Find all
GET http://localhost:8080/api/v1/todo

### Find by id
GET http://localhost:8080/api/v1/todo/5617844b-1bdc-4ab9-a8ae-cb33bb09c577

### Created
POST http://localhost:8080/api/v1/todo
Content-Type: application/json

{
  "title": "My First Todo",
  "description": "",
  "status": "CREATED"
}

### Updated
PATCH http://localhost:8080/api/v1/todo/5617844b-1bdc-4ab9-a8ae-cb33bb09c577
content-type: application/json

{
  "description": "Add new description"
}

### Deleted
DELETE http://localhost:8080/api/v1/todo/eba1f6fa-7a36-4cd4-a370-e0b4628d0c14

### Helth check
GET http://localhost:8080/healthcheck
